import Head from 'next/head'
import Image from 'next/image'
import ContainerBlock from '../components/ContainerBlock'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerBlock>

        <div className='py-20 bg-[#E4F0D8]'>
          <div className='flex lg:w-8/12 w-11/12 mx-auto '>
            <div className='lg:w-6/12'>
              <p className='text-6xl font-Bungee text-yellow-500'>Food for a good mood</p>
            </div>
            <div className='lg:w-6/12 flex justify-end'>
              <img src='./packet.png' className=''/>
            </div>
          </div>
        </div>
      </ContainerBlock>
    </div>
  )
}
